#!/usr/bin/make -f

NAME = ShredZone

FILES_DSP = \
	ShredZonePlugin.cpp

FILES_UI = \
	ShredZone_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
