#!/usr/bin/make -f
NAME = StudioWahFilter
FILES_DSP = StudioWahFilterPlugin.cpp
FILES_UI = StudioWahFilter_ui.cpp
DPF_PATH ?= ../DPF
include $(DPF_PATH)/Makefile.plugins.mk
TARGETS += vst3
all: $(TARGETS)
