"""NAM Rig Builder — map Rocksmith tones to NAM presets via tone3000.

Sits between the `tones` plugin (which parses gear chains out of CDLC)
and the bundled `nam_tone` plugin (which owns the preset database and
audio engine bindings). This plugin:

  1. Parses Rocksmith tone chains from PSARC/sloppak files.
  2. Translates each gear piece to a real make/model via rs_to_real.json
     (generated by extract_gear_map.py from the game's own gears.psarc).
  3. Either suggests tone3000 captures (if an API key is present) or
     gives the user a deep-link to tone3000's web search.
  4. Persists the chosen amp .nam / cab IR into nam_tone.db so the
     NAM runtime picks them up automatically when playing the song.

A `preset_pieces` table extends nam_tone.db with the full Rocksmith
chain (pedals/racks/etc.) — informational in v0; the runtime today
only consumes the primary amp/cab pair encoded in `presets`.
"""

import base64
import json
import logging
import sqlite3
import subprocess
import sys
import threading
import time
import urllib.request
from pathlib import Path

from fastapi import Body, UploadFile, File
from fastapi.responses import JSONResponse, Response

log = logging.getLogger("slopsmith.plugin.nam_rig_builder")

_plugin_dir = Path(__file__).parent

# Module-level singletons populated by setup(). They start as None so
# tests / linting on import don't blow up; _require_*() helpers turn
# accidental pre-setup access into clear errors instead of AttributeError.
_config_dir: Path | None = None
_get_dlc_dir = None
_get_sloppak_cache_dir = None
_db_path: str | None = None
_conn: sqlite3.Connection | None = None
_lock = threading.Lock()

_rs_to_real: dict | None = None
_rs_cab_to_ir: dict | None = None
_settings: dict | None = None  # tone3000_api_key, min_downloads, aggressive

# tone3000 client is recreated when the user updates settings, so we
# wrap construction in a lock to avoid two threads racing during a
# concurrent batch + settings change.
_t3k_client = None
_t3k_lock = threading.Lock()

# Background batch job state. The web layer polls _batch_state via
# /batch_status; only the worker thread mutates it (under _batch_lock).
_batch_state: dict = {
    "running": False,
    "progress": 0,
    "total": 0,
    "log": [],
    "assigned": 0,
    "skipped": 0,
    "pending": [],
    "started_at": None,
    "finished_at": None,
}
_batch_lock = threading.Lock()
_batch_thread: threading.Thread | None = None


# ── Constants ────────────────────────────────────────────────────────

# Settings file inside the slopsmith config dir. Kept separate from
# nam_tone.db because it's user preferences (with secrets) rather than
# tone data, and so a corrupted DB doesn't lose the API key.
_SETTINGS_FILENAME = "nam_rig_builder_settings.json"

_DEFAULT_SETTINGS = {
    "tone3000_api_key": "",
    "min_downloads": 50,
    "aggressive": False,
    # v3 auto-download knobs.
    "preferred_size": "standard",       # standard | lite | feather | nano
    "auto_download": True,              # batch downloads files instead of just recording IDs
    "disk_budget_mb": 2000,             # stop batch downloads once we cross this many MB
    "auto_watch": True,                 # background watcher auto-downloads songs as they materialize
}

# Tone3000 platform value to request per Rocksmith category. Amps and
# (most) pedals/racks get NAM captures; cabinets are convolved with IRs.
_PLATFORM_FOR_CATEGORY = {
    "amp": "nam",
    "pedal": "nam",
    "rack": "nam",
    "cab": "ir",
}


# ── Helpers ──────────────────────────────────────────────────────────


def _require_db_path() -> str:
    if _db_path is None:
        raise RuntimeError("nam_rig_builder plugin not initialized")
    return _db_path


def _get_conn() -> sqlite3.Connection:
    """Open (and migrate, if needed) the shared nam_tone.db.

    The nam_tone plugin already creates `presets` and `tone_mappings`;
    we additionally ensure `preset_pieces` exists. CREATE TABLE IF NOT
    EXISTS is idempotent, so running this every cold start is safe.
    """
    global _conn
    if _conn is None:
        _conn = sqlite3.connect(_require_db_path(), check_same_thread=False)
        _conn.execute("PRAGMA journal_mode=WAL")
        _conn.execute("PRAGMA foreign_keys=ON")
        _conn.execute(
            """
            CREATE TABLE IF NOT EXISTS preset_pieces (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                preset_id INTEGER NOT NULL,
                slot_order INTEGER NOT NULL,
                slot TEXT NOT NULL,
                rs_gear_type TEXT NOT NULL,
                kind TEXT NOT NULL,
                file TEXT,
                params_json TEXT NOT NULL DEFAULT '{}',
                tone3000_id INTEGER,
                assigned_mode TEXT,
                bypassed INTEGER NOT NULL DEFAULT 0,
                FOREIGN KEY (preset_id) REFERENCES presets(id) ON DELETE CASCADE
            )
            """
        )
        # Migrate older DBs that predate the `bypassed` column. ALTER TABLE
        # ADD COLUMN is not idempotent, so guard on the column list.
        cols = {r[1] for r in _conn.execute("PRAGMA table_info(preset_pieces)")}
        if "bypassed" not in cols:
            _conn.execute(
                "ALTER TABLE preset_pieces ADD COLUMN bypassed INTEGER NOT NULL DEFAULT 0"
            )
        _conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_preset_pieces_preset "
            "ON preset_pieces(preset_id)"
        )
        _conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_preset_pieces_rs_gear "
            "ON preset_pieces(rs_gear_type)"
        )
        _conn.commit()
    return _conn


def _load_settings() -> dict:
    global _settings
    if _settings is not None:
        return _settings
    if _config_dir is None:
        return dict(_DEFAULT_SETTINGS)
    path = _config_dir / _SETTINGS_FILENAME
    if path.exists():
        try:
            loaded = json.loads(path.read_text())
            _settings = {**_DEFAULT_SETTINGS, **loaded}
        except (json.JSONDecodeError, OSError):
            log.warning("settings file unreadable, resetting to defaults")
            _settings = dict(_DEFAULT_SETTINGS)
    else:
        _settings = dict(_DEFAULT_SETTINGS)
    return _settings


def _save_settings(new_settings: dict) -> dict:
    global _settings, _t3k_client
    if _config_dir is None:
        raise RuntimeError("config_dir not available")
    current = _load_settings()
    merged = {**current, **new_settings}
    (_config_dir / _SETTINGS_FILENAME).write_text(json.dumps(merged, indent=2))
    _settings = merged
    # Reset the cached client so a new key takes effect immediately.
    with _t3k_lock:
        _t3k_client = None
    return merged


def _get_t3k_client():
    """Lazy tone3000 client. Cached because we open a sqlite cache db on
    construction. Reset when settings change."""
    global _t3k_client
    with _t3k_lock:
        if _t3k_client is None:
            # Import here so that a missing client module doesn't break
            # the plugin's main routes — search just degrades.
            sys.path.insert(0, str(_plugin_dir))
            from tone3000_client import Tone3000Client
            settings = _load_settings()
            cache_path = str(_config_dir / "nam_rig_builder_cache.db") if _config_dir else "/tmp/nam_rig_builder_cache.db"
            _t3k_client = Tone3000Client(
                cache_path,
                api_key=settings.get("tone3000_api_key") or None,
            )
        return _t3k_client


def _load_rs_to_real() -> dict:
    """Load (and cache) the rs_to_real.json map. Returns an empty dict
    if the user hasn't run extract_gear_map.py yet — the UI surfaces
    that case as a "needs setup" banner."""
    global _rs_to_real
    if _rs_to_real is None:
        path = _plugin_dir / "rs_to_real.json"
        if path.exists():
            try:
                _rs_to_real = json.loads(path.read_text())
            except json.JSONDecodeError:
                log.error("rs_to_real.json is corrupt", exc_info=True)
                _rs_to_real = {}
        else:
            _rs_to_real = {}
    return _rs_to_real


def _invalidate_rs_to_real() -> None:
    global _rs_to_real
    _rs_to_real = None


def _load_rs_cab_to_ir() -> dict:
    """Load (and cache) the rs_cab_to_ir.json map produced by
    extract_irs.py. Each key is a Rocksmith gear entity (e.g.
    `Cab_4x12_AT_CL`) whose sound bank held embedded IRs in
    gears.psarc; the value is `{sound_bank, irs: [relpaths under
    nam_irs/], category}`.

    Returns an empty dict if extraction hasn't been run. The deep-link
    path still works without it; this is purely a "do we have a local
    IR for this cab?" lookup.
    """
    global _rs_cab_to_ir
    if _rs_cab_to_ir is None:
        path = _plugin_dir / "rs_cab_to_ir.json"
        if path.exists():
            try:
                _rs_cab_to_ir = json.loads(path.read_text())
            except json.JSONDecodeError:
                log.error("rs_cab_to_ir.json is corrupt", exc_info=True)
                _rs_cab_to_ir = {}
        else:
            _rs_cab_to_ir = {}
    return _rs_cab_to_ir


def _invalidate_rs_cab_to_ir() -> None:
    global _rs_cab_to_ir
    _rs_cab_to_ir = None


# ── Tone parsing (mirrors plugins/tones/routes.py logic) ─────────────
#
# We intentionally re-implement here rather than import from the tones
# plugin: plugin-to-plugin imports require path acrobatics that fragile
# across slopsmith versions, and the parsing surface is small enough
# that copying is cheaper than coupling. Gear images are still served
# by the tones plugin (`/api/plugins/tones/gear-image/{type}`).


def _extract_model_from_knobs(knobs: dict) -> str | None:
    if not knobs:
        return None
    first_knob = next(iter(knobs))
    parts = first_knob.split("_")
    if len(parts) >= 3:
        rs_map = _load_rs_to_real()
        for i in range(len(parts) - 1, 0, -1):
            candidate = "_".join(parts[:i])
            if candidate in rs_map:
                return candidate
        return "_".join(parts[:-1])
    if len(parts) == 2:
        return parts[0]
    return None


def _parse_gear(gear: dict, slot_type: str) -> dict:
    gear_type = gear.get("Type", "")
    knobs = gear.get("KnobValues", {}) or {}
    category = gear.get("Category", "")

    model_key = _extract_model_from_knobs(knobs) or gear_type

    clean_knobs: dict = {}
    for k, v in knobs.items():
        parts = k.split("_")
        clean_name = parts[-1] if len(parts) > 1 else k
        clean_knobs[clean_name] = round(v, 1) if isinstance(v, float) else v

    return {
        "type": model_key,
        "slot": slot_type,
        "category": category,
        "knobs": clean_knobs,
    }


def _parse_tone(tone_data: dict) -> dict:
    name = tone_data.get("Name", "Unknown")
    key = tone_data.get("Key", "")
    gear_list = tone_data.get("GearList", {}) or {}

    chain: list[dict] = []
    for slot in ("PrePedal1", "PrePedal2", "PrePedal3", "PrePedal4"):
        g = gear_list.get(slot)
        if g and g.get("Type"):
            chain.append(_parse_gear(g, "pre_pedal"))

    g = gear_list.get("Amp")
    if g and g.get("Type"):
        chain.append(_parse_gear(g, "amp"))

    for slot in ("PostPedal1", "PostPedal2", "PostPedal3", "PostPedal4"):
        g = gear_list.get(slot)
        if g and g.get("Type"):
            chain.append(_parse_gear(g, "post_pedal"))

    for slot in ("Rack1", "Rack2", "Rack3", "Rack4"):
        g = gear_list.get(slot)
        if g and g.get("Type"):
            chain.append(_parse_gear(g, "rack"))

    g = gear_list.get("Cabinet")
    if g and g.get("Type"):
        chain.append(_parse_gear(g, "cabinet"))

    return {"name": name, "key": key, "chain": chain}


def _enrich_chain_piece(piece: dict) -> dict:
    """Add make/model + tone3000 hints + existing-assignment info to a
    parsed chain piece. Returns a new dict, doesn't mutate input."""
    rs_type = piece["type"]
    rs_map = _load_rs_to_real()
    info = rs_map.get(rs_type) or {}

    category = info.get("category") or _guess_category_from_slot(piece["slot"])
    platform = _PLATFORM_FOR_CATEGORY.get(category, "nam")

    query = info.get("tone3000_query") or rs_type
    gears = info.get("tone3000_gears") or ""

    from tone3000_client import Tone3000Client  # local import (same dir)
    deep_link = Tone3000Client.build_search_url(query, gears=gears or None, platform=platform)

    # Lookup any preset_piece already saved for this rs_gear. Prefer a
    # row that actually has a file over a pending one (kind='none' /
    # empty file), then the most recent — otherwise a stale pending row
    # for the same gear (e.g. left by a batch on another song) would
    # shadow a real assignment and the chain would wrongly show
    # "(no file)" even though the capture is downloaded.
    assigned = None
    conn = _get_conn()
    row = conn.execute(
        "SELECT id, preset_id, kind, file, tone3000_id, assigned_mode "
        "FROM preset_pieces WHERE rs_gear_type = ? "
        "ORDER BY (CASE WHEN file IS NOT NULL AND file != '' THEN 0 ELSE 1 END), id DESC "
        "LIMIT 1",
        (rs_type,),
    ).fetchone()
    if row:
        assigned = {
            "preset_piece_id": row[0],
            "preset_id": row[1],
            "kind": row[2],
            "file": row[3],
            "tone3000_id": row[4],
            "assigned_mode": row[5],
        }

    # Rocksmith-extracted IRs: only meaningful for cab slots. The map
    # is keyed by the same entity name we have in rs_to_real, so it's
    # a direct lookup. We filter by on-disk existence so a fresh
    # install that ships `rs_cab_to_ir.json` without the .wav files
    # (e.g. a user that doesn't own Rocksmith and so hasn't run
    # extract_irs.py) doesn't surface broken references — the UI just
    # falls back to the tone3000 deep-link for that cab.
    rs_irs: list[str] = []
    if category == "cab":
        rs_entry = _load_rs_cab_to_ir().get(rs_type) or {}
        candidates = list(rs_entry.get("irs") or [])
        irs_root = _config_dir / "nam_irs" if _config_dir else None
        if irs_root:
            rs_irs = [f for f in candidates if (irs_root / f).exists()]

    return {
        **piece,
        "real_name": info.get("name", rs_type),
        "make": info.get("make", ""),
        "model": info.get("model", ""),
        "rs_category": category,
        "tone3000_query": query,
        "tone3000_gears": gears,
        "tone3000_platform": platform,
        "tone3000_search_url": deep_link,
        "rs_irs": rs_irs,
        "assigned": assigned,
    }


def _guess_category_from_slot(slot: str) -> str:
    if slot == "amp":
        return "amp"
    if slot == "cabinet":
        return "cab"
    if slot == "rack":
        return "rack"
    return "pedal"


# ── PSARC / sloppak readers ──────────────────────────────────────────


def _read_tones_from_psarc(psarc_path: Path) -> list[dict]:
    """Return raw RS tone definitions from a PSARC's arrangement JSON."""
    from psarc import read_psarc_entries
    files = read_psarc_entries(str(psarc_path), ["*.json"])
    tones: list[dict] = []
    seen_keys: set[str] = set()
    for path, data in sorted(files.items()):
        if not path.endswith(".json"):
            continue
        try:
            j = json.loads(data)
        except json.JSONDecodeError:
            import re
            text = data.decode("utf-8", errors="ignore")
            text = re.sub(r",\s*([}\]])", r"\1", text)
            try:
                j = json.loads(text)
            except Exception:
                continue
        for _, v in j.get("Entries", {}).items():
            attrs = v.get("Attributes", {}) or {}
            arr_name = attrs.get("ArrangementName", "")
            if arr_name in ("Vocals", "ShowLights", "JVocals"):
                continue
            for t in attrs.get("Tones", []) or []:
                key = t.get("Key", "")
                if isinstance(key, str) and key:
                    if key in seen_keys:
                        continue
                    seen_keys.add(key)
                tones.append(t)
    return tones


def _read_tones_from_sloppak(filename: str, dlc: Path) -> list[dict]:
    try:
        import sloppak as sloppak_mod
    except ImportError:
        return []
    cache_dir = _get_sloppak_cache_dir() if _get_sloppak_cache_dir else None
    if not cache_dir and _config_dir:
        cache_dir = _config_dir / "sloppak_cache"
    try:
        loaded = sloppak_mod.load_song(filename.rstrip("/\\"), dlc, cache_dir)
    except Exception:
        log.warning("failed to read sloppak %r", filename, exc_info=True)
        return []
    tones: list[dict] = []
    seen: set[str] = set()
    for arr in loaded.song.arrangements:
        if arr.name in ("Vocals", "ShowLights", "JVocals"):
            continue
        arr_tones = getattr(arr, "tones", None) or {}
        for t in arr_tones.get("definitions") or []:
            if not isinstance(t, dict):
                continue
            key = t.get("Key", "")
            if isinstance(key, str) and key:
                if key in seen:
                    continue
                seen.add(key)
            tones.append(t)
    return tones


def _resolve_song_file(filename: str) -> Path | None:
    """Return the PSARC/sloppak path inside DLC_DIR, or None if invalid."""
    dlc = _get_dlc_dir() if _get_dlc_dir else None
    if not dlc:
        return None
    candidate = (dlc / filename).resolve()
    try:
        candidate.relative_to(dlc.resolve())
    except (OSError, ValueError):
        return None
    if not candidate.exists():
        return None
    return candidate


# ── v3 auto-download: tone3000 model → nam_models/ or nam_irs/ ───────


def _safe_filename(text: str) -> str:
    """Make a string safe to use as a filename leaf.

    Used to derive stable filenames from tone3000 IDs/titles. We keep
    ascii letters/digits and a few separators; everything else
    collapses to underscore so the result is portable across the
    filesystems the plugin runs on (HFS+, APFS, ext4, NTFS).
    """
    out: list[str] = []
    for ch in text:
        if ch.isalnum() or ch in "-_.":
            out.append(ch)
        elif ch in " /\\":
            out.append("_")
    cleaned = "".join(out).strip("._")
    return cleaned or "file"


def _ffmpeg_normalize_ir(src: Path, dest: Path) -> bool:
    """Run a downloaded IR through ffmpeg to 48 kHz mono float32 WAV.

    Mirrors what nam_tone's /irs upload endpoint does to user-supplied
    IRs — anything looser (different sample rate, stereo, int16, opus
    inside a .wav-named container) confuses the browser's
    decodeAudioData and the IR fails silently at playback.

    Returns True on success. On failure (ffmpeg missing, decode error,
    timeout) the caller falls back to a raw byte copy.
    """
    try:
        result = subprocess.run(
            [
                "ffmpeg", "-y", "-i", str(src),
                "-ar", "48000", "-ac", "1",
                "-c:a", "pcm_f32le",
                str(dest),
            ],
            capture_output=True,
            timeout=60,
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


# Tracks how many bytes the current batch has pulled. Reset at the
# start of each batch run.
_batch_disk_bytes = 0


def _disk_budget_reached(settings: dict) -> bool:
    cap_mb = int(settings.get("disk_budget_mb", 2000) or 0)
    if cap_mb <= 0:
        return False
    return _batch_disk_bytes >= cap_mb * 1024 * 1024


def _download_candidate(
    *,
    tone3000_id: int,
    is_ir: bool,
    rs_gear: str,
    settings: dict,
) -> tuple[str, str] | None:
    """Download the best model for a tone3000 tone id and stage it in
    the right nam_tone directory.

    Returns `(kind, relative_path)` to put into a preset_piece, or
    None if no model was available, the download failed, or the disk
    budget was exhausted. `kind` is `'nam'` for amp/pedal/rack and
    `'ir'` for cabinet, matching the values nam_tone's runtime
    understands.

    The function is idempotent across batch runs: filenames embed the
    tone3000 tone+model id, so once a file is on disk subsequent
    batches skip the network entirely (the client's
    download_model_file is itself idempotent on dest existence).
    """
    global _batch_disk_bytes
    if _disk_budget_reached(settings):
        return None

    client = _get_t3k_client()
    if not client.has_api_access:
        return None

    try:
        models_payload = client.list_models(tone3000_id)
    except Exception:
        log.warning("list_models failed for tone_id=%s", tone3000_id, exc_info=True)
        return None
    if not models_payload:
        return None

    from tone3000_client import pick_best_model
    model = pick_best_model(models_payload, preferred_size=settings.get("preferred_size", "standard"))
    if not model:
        return None

    model_url = model.get("model_url") or ""
    if not model_url:
        return None
    model_id = model.get("id")

    if is_ir:
        # tone3000 IRs come in various formats; nam_tone wants 48k
        # mono float32 WAV. We stage to a temp path, normalize, and
        # only count bytes against the budget once the final file
        # exists.
        irs_dir = _config_dir / "nam_irs"
        irs_dir.mkdir(parents=True, exist_ok=True)
        final_name = f"tone3000_{tone3000_id}_m{model_id}_{_safe_filename(rs_gear)}.wav"
        final_path = irs_dir / final_name
        if final_path.exists():
            return ("ir", final_name)
        tmp_path = irs_dir / (final_name + ".raw")
        try:
            client.download_model_file(model_url, str(tmp_path))
        except Exception:
            log.warning("IR download failed for %s", rs_gear, exc_info=True)
            try:
                tmp_path.unlink(missing_ok=True)
            except Exception:
                pass
            return None
        ok = _ffmpeg_normalize_ir(tmp_path, final_path)
        try:
            tmp_path.unlink(missing_ok=True)
        except Exception:
            pass
        if not ok:
            log.warning("ffmpeg normalization failed for %s — IR not assigned", rs_gear)
            try:
                final_path.unlink(missing_ok=True)
            except Exception:
                pass
            return None
        _batch_disk_bytes += final_path.stat().st_size
        return ("ir", final_name)

    # NAM model — drop straight into nam_models/.
    models_dir = _config_dir / "nam_models"
    models_dir.mkdir(parents=True, exist_ok=True)
    final_name = f"tone3000_{tone3000_id}_m{model_id}_{_safe_filename(rs_gear)}.nam"
    final_path = models_dir / final_name
    if final_path.exists():
        return ("nam", final_name)
    try:
        written = client.download_model_file(model_url, str(final_path))
    except Exception:
        log.warning("NAM download failed for %s", rs_gear, exc_info=True)
        try:
            final_path.unlink(missing_ok=True)
        except Exception:
            pass
        return None
    _batch_disk_bytes += written
    return ("nam", final_name)


# ── Persistence: presets + preset_pieces + tone_mappings ─────────────


def _persist_preset_chain(
    *,
    filename: str,
    tone_key: str,
    name: str,
    pieces: list[dict],
    input_gain: float = 1.0,
    output_gain: float = 0.5,
    gate_threshold: float = -60.0,
    assigned_mode: str = "manual",
) -> int:
    """Insert/replace a preset + chain pieces + tone mapping. Returns
    the preset id.

    The "primary" amp piece (first piece with kind=nam) becomes the
    preset's `model_file`; the first IR piece becomes `ir_file`. That's
    what the existing nam_tone runtime reads. Everything else goes
    into preset_pieces for the UI and future multi-stage support.
    """
    conn = _get_conn()
    # The nam_tone runtime only consumes one model + one IR per preset
    # (see nam_tone/routes.py:get_native_preset — single NAM + single IR;
    # multi-stage chains aren't supported by the audio engine). Pick the
    # primary NAM by slot priority. Only amp/rack are eligible: a pedal
    # NAM must NEVER be promoted to the sole "amp", or a song whose amp
    # is still unmapped but whose pedal got a capture plays the pedal as
    # if it were the amp (wrong/weak tone). With no amp/rack NAM the
    # primary stays empty and the amp surfaces as pending instead.
    # A bypassed piece is excluded from the primary model/IR too, so the
    # bundle's single-NAM runtime stays consistent with the saved bypass
    # (e.g. bypassing the amp leaves no primary, rather than playing it).
    _MODEL_PRIORITY = _MODEL_SLOT_PRIORITY
    primary_model = ""
    for slot in _MODEL_PRIORITY:
        for p in pieces:
            if (
                p.get("slot") == slot
                and p.get("kind") == "nam"
                and p.get("file")
                and not p.get("bypassed")
            ):
                primary_model = p["file"]
                break
        if primary_model:
            break
    primary_ir = ""
    for p in pieces:
        if (p.get("slot") == "cabinet" and p.get("kind") in ("ir", "rs_ir")
                and p.get("file") and not p.get("bypassed")):
            primary_ir = p["file"]
            break
    if not primary_ir:
        # Fall back to any IR if no cabinet-slot IR was provided (e.g.
        # the user supplied an IR for a rack slot instead).
        for p in pieces:
            if p.get("kind") in ("ir", "rs_ir") and p.get("file") and not p.get("bypassed"):
                primary_ir = p["file"]
                break

    with _lock:
        cur = conn.execute(
            "INSERT INTO presets (name, model_file, ir_file, input_gain, output_gain, gate_threshold, settings_json) "
            "VALUES (?, ?, ?, ?, ?, ?, ?) "
            "ON CONFLICT(name) DO UPDATE SET "
            "  model_file=excluded.model_file, ir_file=excluded.ir_file, "
            "  input_gain=excluded.input_gain, output_gain=excluded.output_gain, "
            "  gate_threshold=excluded.gate_threshold",
            (name, primary_model, primary_ir, input_gain, output_gain, gate_threshold, "{}"),
        )
        preset_id_row = conn.execute(
            "SELECT id FROM presets WHERE name = ?", (name,)
        ).fetchone()
        preset_id = int(preset_id_row[0])

        # Replace chain (delete + insert) — simpler than diffing.
        conn.execute("DELETE FROM preset_pieces WHERE preset_id = ?", (preset_id,))
        for i, p in enumerate(pieces):
            conn.execute(
                "INSERT INTO preset_pieces "
                "(preset_id, slot_order, slot, rs_gear_type, kind, file, params_json, tone3000_id, assigned_mode, bypassed) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (
                    preset_id,
                    i,
                    p.get("slot", ""),
                    p.get("rs_gear_type", ""),
                    p.get("kind", "none"),
                    p.get("file"),
                    json.dumps(p.get("params", {})),
                    p.get("tone3000_id"),
                    p.get("assigned_mode", assigned_mode),
                    1 if p.get("bypassed") else 0,
                ),
            )

        conn.execute(
            "INSERT OR REPLACE INTO tone_mappings (filename, tone_key, preset_id) VALUES (?, ?, ?)",
            (filename, tone_key, preset_id),
        )
        conn.commit()

    return preset_id


# Slot priority for choosing a preset's primary NAM. Shared by
# _persist_preset_chain and _recompute_preset_primaries. Pedals
# (pre_pedal/post_pedal) are intentionally excluded: the engine plays a
# single NAM, and a pedal capture standing in for a missing amp sounds
# wrong. Only an amp (or a rack pre/power amp) may be the primary model.
_MODEL_SLOT_PRIORITY = ("amp", "rack")


# Order in which chain pieces are sent to the audio engine as type-1 NAM
# stages: signal-flow order pre_pedal → amp → post_pedal → rack. (Used
# only by the experimental full-chain preview endpoint below — the
# persisted presets still expose a single primary NAM for the bundle's
# 2-stage runtime.)
_CHAIN_NAM_ORDER = ("pre_pedal", "amp", "post_pedal", "rack")


def _state_b64(data: dict) -> str:
    """Base64 of compact JSON — byte-identical to nam_tone's _state_b64,
    which the native engine expects for each chain stage's `state`."""
    payload = json.dumps(data, separators=(",", ":")).encode("utf-8")
    return base64.b64encode(payload).decode("ascii")


def _safe_child(root: Path | None, name: str | None) -> Path | None:
    """Resolve `name` under `root`, refusing path-escape. Mirrors
    nam_tone._safe_child so the engine gets the same absolute paths."""
    if not root or not name:
        return None
    root_resolved = root.resolve()
    path = (root / name).resolve()
    try:
        path.relative_to(root_resolved)
    except ValueError:
        return None
    return path


def _tone_image_index() -> dict:
    """Map tone3000 tone_id -> {title, image, gear} from the LOCAL search
    cache, so the gear catalog can show a photo for an assigned capture
    without extra network calls. Best-effort; empty if the cache is absent.
    tone3000's Tone objects carry an `images` array of public URLs."""
    idx: dict[int, dict] = {}
    if _config_dir is None:
        return idx
    cache = _config_dir / "nam_rig_builder_cache.db"
    if not cache.exists():
        return idx
    try:
        c = sqlite3.connect(f"file:{cache}?mode=ro", uri=True)
        try:
            for (rj,) in c.execute("SELECT response_json FROM search_cache"):
                try:
                    data = json.loads(rj)
                except Exception:
                    continue
                if not isinstance(data, dict):
                    continue
                for t in (data.get("data") or []):
                    if (isinstance(t, dict) and isinstance(t.get("id"), int)
                            and t["id"] not in idx):
                        imgs = t.get("images") or []
                        idx[t["id"]] = {
                            "title": t.get("title"),
                            "image": imgs[0] if imgs else None,
                            "gear": t.get("gear"),
                        }
        finally:
            c.close()
    except Exception:
        log.debug("tone image index unavailable", exc_info=True)
    return idx


def _recompute_preset_primaries(conn: sqlite3.Connection, preset_id: int) -> None:
    """Re-derive `presets.model_file` / `ir_file` from the preset's
    current `preset_pieces`, using the same slot priority as
    `_persist_preset_chain`. The nam_tone runtime only plays those two
    columns, so this is what makes a freshly-assigned piece audible.

    Caller must already hold `_lock`.
    """
    rows = conn.execute(
        "SELECT slot, kind, file, bypassed FROM preset_pieces "
        "WHERE preset_id = ? ORDER BY slot_order",
        (preset_id,),
    ).fetchall()
    # Bypassed pieces are excluded from the primary model/IR (consistent
    # with _persist_preset_chain and the saved bypass state).
    pieces = [
        {"slot": r[0], "kind": r[1], "file": r[2]}
        for r in rows if not r[3]
    ]

    model_file = ""
    for slot in _MODEL_SLOT_PRIORITY:
        for p in pieces:
            if p["slot"] == slot and p["kind"] == "nam" and p["file"]:
                model_file = p["file"]
                break
        if model_file:
            break
    ir_file = ""
    for p in pieces:
        if p["slot"] == "cabinet" and p["kind"] in ("ir", "rs_ir") and p["file"]:
            ir_file = p["file"]
            break
    if not ir_file:
        for p in pieces:
            if p["kind"] in ("ir", "rs_ir") and p["file"]:
                ir_file = p["file"]
                break

    conn.execute(
        "UPDATE presets SET model_file = ?, ir_file = ? WHERE id = ?",
        (model_file, ir_file, preset_id),
    )


def _assign_file_to_gear(
    rs_gear: str, kind: str, file: str, tone3000_id: int | None = None,
) -> dict:
    """Stamp a downloaded file onto every *pending* preset_pieces row for
    `rs_gear` and refresh the affected presets' primary model/IR.

    This is what moves a gear out of the Pendientes list after a manual
    "Download and assign": the coverage query counts a gear as pending
    while any of its pieces has `kind='none'` or an empty `file`, and
    the nam_tone runtime only plays `presets.model_file` / `ir_file`.
    Updating just the pieces (as the old code implicitly relied on the
    song-view "Save preset" step to do) left both stale, so the gear
    stayed pending and the song kept playing the generic synth.

    Returns `{pieces_updated, presets_updated}`. If the gear has no
    preset rows yet (never batched/saved), both are 0 and the caller's
    downloaded file is still returned for the song-view flow to use.
    """
    conn = _get_conn()
    with _lock:
        affected = [
            r[0] for r in conn.execute(
                "SELECT DISTINCT preset_id FROM preset_pieces "
                "WHERE rs_gear_type = ? AND (kind = 'none' OR file IS NULL OR file = '')",
                (rs_gear,),
            ).fetchall()
        ]
        cur = conn.execute(
            "UPDATE preset_pieces "
            "SET kind = ?, file = ?, tone3000_id = ?, assigned_mode = 'manual' "
            "WHERE rs_gear_type = ? AND (kind = 'none' OR file IS NULL OR file = '')",
            (kind, file, tone3000_id, rs_gear),
        )
        pieces_updated = cur.rowcount
        for pid in affected:
            _recompute_preset_primaries(conn, pid)
        conn.commit()
    return {"pieces_updated": pieces_updated, "presets_updated": len(affected)}


# ── Batch job ───────────────────────────────────────────────────────


def _batch_log(msg: str) -> None:
    with _batch_lock:
        _batch_state["log"].append(f"{time.strftime('%H:%M:%S')} {msg}")
        # Keep log bounded so memory doesn't grow on huge libraries.
        if len(_batch_state["log"]) > 500:
            _batch_state["log"] = _batch_state["log"][-500:]


def _list_library_songs() -> tuple[list[Path], int]:
    """Return (parseable songs, count of cloud-only placeholders).

    Cloud-loader users have a DLC dir full of 0-byte PSARC stubs —
    metadata exists in Slopsmith's library DB, but the actual archive
    isn't on disk until the user plays the song (or runs cloud_loader's
    materialize action). Trying to parse those stubs floods the batch
    log with "Not a PSARC file" errors and slows nothing down, so we
    filter them out here and report the count separately so the UI
    can tell the user how many songs they'd need to materialize for
    a full library scan.
    """
    dlc = _get_dlc_dir() if _get_dlc_dir else None
    if not dlc:
        return [], 0
    songs: list[Path] = []
    cloud_only = 0
    for p in sorted(dlc.iterdir()):
        if p.suffix.lower() not in (".psarc", ".sloppak"):
            continue
        try:
            if p.stat().st_size == 0:
                cloud_only += 1
                continue
        except OSError:
            continue
        songs.append(p)
    return songs, cloud_only


def _batch_worker():
    """Library-wide auto-assign: unique gear → tone3000 candidate (if
    API access) → recorded as 'pending' otherwise. No downloads run in
    the v0 worker — that's the user's manual step. We still create
    `preset_pieces` rows with kind='none' so the Pendientes tab knows
    what's outstanding.
    """
    global _batch_disk_bytes
    try:
        _batch_disk_bytes = 0
        with _batch_lock:
            _batch_state["started_at"] = time.time()
            _batch_state["log"] = []

        songs, cloud_only = _list_library_songs()
        with _batch_lock:
            _batch_state["total"] = len(songs)
            _batch_state["progress"] = 0
            _batch_state["assigned"] = 0
            _batch_state["skipped"] = 0
            _batch_state["cloud_only"] = cloud_only
            _batch_state["pending"] = []

        _batch_log(f"Found {len(songs)} materialized songs (parseable)")
        if cloud_only:
            _batch_log(
                f"Skipping {cloud_only} cloud-only placeholders (0-byte stubs). "
                "Play them through Slopsmith or use cloud_loader → materialize "
                "to pull them onto disk first."
            )
        rs_map = _load_rs_to_real()
        if not rs_map:
            _batch_log("rs_to_real.json missing — run extract first")
            return

        client = _get_t3k_client()
        settings = _load_settings()
        rs_irs_map = _load_rs_cab_to_ir()
        seen_gears: dict[str, dict] = {}  # rs_gear_type → top tone3000 candidate or {}

        for idx, song_path in enumerate(songs):
            with _batch_lock:
                _batch_state["progress"] = idx + 1
            filename = song_path.name

            try:
                if song_path.suffix.lower() == ".sloppak":
                    tones = _read_tones_from_sloppak(filename, song_path.parent)
                else:
                    tones = _read_tones_from_psarc(song_path)
            except Exception as e:
                _batch_log(f"skip {filename}: {type(e).__name__}: {e}")
                with _batch_lock:
                    _batch_state["skipped"] += 1
                continue

            for tone in tones:
                parsed = _parse_tone(tone)
                tone_key = parsed["key"]
                preset_name = f"{filename}::{tone_key}" if tone_key else f"{filename}::{parsed['name']}"
                pieces: list[dict] = []

                for piece in parsed["chain"]:
                    rs_type = piece["type"]
                    info = rs_map.get(rs_type) or {}
                    category = info.get("category") or _guess_category_from_slot(piece["slot"])
                    gears = info.get("tone3000_gears") or ""
                    query = info.get("tone3000_query") or rs_type
                    platform = _PLATFORM_FOR_CATEGORY.get(category, "nam")

                    # Cabs first: if we extracted a Rocksmith IR for
                    # this gear AND it's actually on disk, assign it.
                    # Saves a tone3000 round-trip and gives the user
                    # the game's own sound out of the box. Skip if the
                    # .wav file doesn't exist locally — the mapping
                    # ships with the plugin but the actual IR assets
                    # don't, so a fresh install without Rocksmith
                    # falls through to the deep-link path below.
                    rs_ir_entry = rs_irs_map.get(rs_type) or {}
                    rs_ir_files = rs_ir_entry.get("irs") or []
                    irs_root = _config_dir / "nam_irs"
                    available = [f for f in rs_ir_files if (irs_root / f).exists()]
                    if category == "cab" and available:
                        pieces.append({
                            "slot": piece["slot"],
                            "rs_gear_type": rs_type,
                            "kind": "rs_ir",
                            "file": available[0],  # default to first variant
                            "params": piece["knobs"],
                            "tone3000_id": None,
                            "assigned_mode": "auto",
                        })
                        continue

                    candidate = seen_gears.get(rs_type)
                    if candidate is None:
                        candidate = {}
                        if client.has_api_access and query:
                            try:
                                from tone3000_client import pick_top_candidate
                                resp = client.search_tones(query, gears=gears or None, platform=platform, page_size=5)
                                top = pick_top_candidate(
                                    resp,
                                    aggressive=settings.get("aggressive", False),
                                    min_downloads=settings.get("min_downloads", 50),
                                )
                                if top:
                                    candidate = {"tone3000_id": top.get("id"), "title": top.get("title")}
                                    # v3: auto-download the picked model into
                                    # nam_models/ (or normalized into nam_irs/
                                    # for cab IRs that lacked a Rocksmith IR).
                                    # Result is cached per rs_gear so the
                                    # second song that uses this gear hits the
                                    # cache, not the network.
                                    if settings.get("auto_download", True):
                                        downloaded = _download_candidate(
                                            tone3000_id=top.get("id"),
                                            is_ir=(category == "cab"),
                                            rs_gear=rs_type,
                                            settings=settings,
                                        )
                                        if downloaded:
                                            kind, fname = downloaded
                                            candidate["kind"] = kind
                                            candidate["file"] = fname
                                            _batch_log(f"downloaded {rs_type} → {fname}")
                                        else:
                                            _batch_log(f"no download for {rs_type} (budget? api? no models?)")
                            except Exception:
                                log.warning("tone3000 search failed for %s", rs_type, exc_info=True)
                        seen_gears[rs_type] = candidate

                    pieces.append({
                        "slot": piece["slot"],
                        "rs_gear_type": rs_type,
                        "kind": candidate.get("kind") or "none",
                        "file": candidate.get("file"),
                        "params": piece["knobs"],
                        "tone3000_id": candidate.get("tone3000_id"),
                        "assigned_mode": "auto",
                    })

                _persist_preset_chain(
                    filename=filename,
                    tone_key=tone_key or parsed["name"],
                    name=preset_name,
                    pieces=pieces,
                    assigned_mode="auto",
                )
                with _batch_lock:
                    _batch_state["assigned"] += 1

        _batch_log(f"Done. Unique gear seen: {len(seen_gears)}")
    except Exception:
        log.exception("batch worker crashed")
        _batch_log("ERROR — see server log")
    finally:
        with _batch_lock:
            _batch_state["running"] = False
            _batch_state["finished_at"] = time.time()


# ── Per-song auto-download (shared by endpoint + watcher) ────────────

# Serializes the per-song flow so the background watcher and a manual
# "open song" don't run concurrently — they share the module-level
# `_batch_disk_bytes` budget counter and both call _download_candidate.
_auto_lock = threading.Lock()


def _auto_download_for_song(filename: str, path: Path) -> dict:
    """Parse one song, pick + download tone3000 captures for each gear
    piece, and persist the preset chain. Shared by the
    /auto_download_song endpoint and the materialization watcher.

    The caller must have already checked that `path` exists, is
    non-zero, and that a tone3000 API key is configured. Raises
    ValueError for an unreadable archive; other parse failures
    propagate. Returns the same counts dict the endpoint reports.

    Pieces already assigned in `preset_pieces` are skipped, so calling
    this twice for the same song (watcher + manual open) is idempotent.
    """
    global _batch_disk_bytes
    with _auto_lock:
        settings = _load_settings()
        rs_map = _load_rs_to_real()
        rs_irs_map = _load_rs_cab_to_ir()
        irs_root = _config_dir / "nam_irs"
        client = _get_t3k_client()

        if path.suffix.lower() == ".sloppak":
            raw_tones = _read_tones_from_sloppak(filename, _get_dlc_dir())
        else:
            raw_tones = _read_tones_from_psarc(path)

        # Dedupe gear across the song's tones — the same JCM800 appears
        # in clean + lead + bass, but we only hit tone3000 once. Reset
        # the disk counter since we're acting on a single song.
        _batch_disk_bytes = 0
        seen_gears: dict[str, dict] = {}
        counts = {"processed": 0, "downloaded": 0, "rs_ir_used": 0,
                  "skipped_assigned": 0, "skipped_no_candidate": 0, "failed": 0}

        for raw in raw_tones:
            parsed = _parse_tone(raw)
            tone_key = parsed["key"] or parsed["name"]
            preset_name = f"{filename}::{tone_key}"
            pieces: list[dict] = []
            conn = _get_conn()

            for piece in parsed["chain"]:
                rs_type = piece["type"]
                info = rs_map.get(rs_type) or {}
                category = info.get("category") or _guess_category_from_slot(piece["slot"])
                gears = info.get("tone3000_gears") or ""
                query = info.get("tone3000_query") or rs_type
                platform = _PLATFORM_FOR_CATEGORY.get(category, "nam")

                # Skip pieces that already have a usable assignment in
                # the DB (re-opening a song shouldn't re-download).
                existing = conn.execute(
                    "SELECT kind, file FROM preset_pieces "
                    "WHERE rs_gear_type = ? AND file IS NOT NULL AND file != '' "
                    "ORDER BY id DESC LIMIT 1",
                    (rs_type,),
                ).fetchone()
                if existing:
                    pieces.append({
                        "slot": piece["slot"],
                        "rs_gear_type": rs_type,
                        "kind": existing[0],
                        "file": existing[1],
                        "params": piece["knobs"],
                        "tone3000_id": None,
                        "assigned_mode": "auto",
                    })
                    counts["skipped_assigned"] += 1
                    counts["processed"] += 1
                    continue

                # Cab fast-path: prefer the Rocksmith IR when on disk.
                rs_ir_entry = rs_irs_map.get(rs_type) or {}
                available = [
                    f for f in (rs_ir_entry.get("irs") or [])
                    if (irs_root / f).exists()
                ]
                if category == "cab" and available:
                    pieces.append({
                        "slot": piece["slot"],
                        "rs_gear_type": rs_type,
                        "kind": "rs_ir",
                        "file": available[0],
                        "params": piece["knobs"],
                        "tone3000_id": None,
                        "assigned_mode": "auto",
                    })
                    counts["rs_ir_used"] += 1
                    counts["processed"] += 1
                    continue

                # tone3000 search + download. Dedupe per gear so the
                # same amp appearing in 3 tones only hits the API once.
                cached = seen_gears.get(rs_type)
                if cached is None:
                    cached = {}
                    try:
                        from tone3000_client import pick_top_candidate
                        resp = client.search_tones(
                            query, gears=gears or None, platform=platform, page_size=5,
                        )
                        top = pick_top_candidate(
                            resp,
                            aggressive=settings.get("aggressive", False),
                            min_downloads=settings.get("min_downloads", 50),
                        )
                        if top:
                            cached["tone3000_id"] = top.get("id")
                            downloaded = _download_candidate(
                                tone3000_id=top.get("id"),
                                is_ir=(category == "cab"),
                                rs_gear=rs_type,
                                settings=settings,
                            )
                            if downloaded:
                                cached["kind"], cached["file"] = downloaded
                            else:
                                counts["failed"] += 1
                        else:
                            counts["skipped_no_candidate"] += 1
                    except Exception:
                        log.warning("auto_download_song search failed for %s", rs_type, exc_info=True)
                        counts["failed"] += 1
                    seen_gears[rs_type] = cached

                if cached.get("file"):
                    counts["downloaded"] += 1
                pieces.append({
                    "slot": piece["slot"],
                    "rs_gear_type": rs_type,
                    "kind": cached.get("kind") or "none",
                    "file": cached.get("file"),
                    "params": piece["knobs"],
                    "tone3000_id": cached.get("tone3000_id"),
                    "assigned_mode": "auto",
                })
                counts["processed"] += 1

            _persist_preset_chain(
                filename=filename,
                tone_key=tone_key,
                name=preset_name,
                pieces=pieces,
                assigned_mode="auto",
            )

        return {"ok": True, **counts}


# ── Background materialization watcher ───────────────────────────────

# Polls the DLC dir; when a song flips from a 0-byte cloud stub to real
# content (cloud_loader materialize, a manual copy, another plugin's
# extractor, …) it runs the per-song auto-download so the NAM chain is
# ready before the user hits play in Slopsmith's main view. Decoupled
# from cloud_loader on purpose — it reacts to the file appearing on
# disk, not to any specific code path that produced it.
_WATCH_INTERVAL_SEC = 5
_watcher_thread: threading.Thread | None = None
_watcher_stop = threading.Event()
_watcher_sizes: dict[str, int] = {}     # filename -> size at last tick
_watcher_pending: dict[str, int] = {}   # filename -> size awaiting a stable confirmation
_watcher_state: dict = {
    "running": False,
    "primed": False,
    "fired_count": 0,
    "last_fired": None,
    "last_error": None,
    "interval_sec": _WATCH_INTERVAL_SEC,
}


def _watch_scan_dlc() -> dict[str, int] | None:
    """Return {filename: size} for every PSARC/sloppak in the DLC dir,
    or None if the dir isn't available."""
    dlc = _get_dlc_dir() if _get_dlc_dir else None
    if not dlc:
        return None
    try:
        entries = sorted(dlc.iterdir())
    except OSError:
        return None
    current: dict[str, int] = {}
    for p in entries:
        if p.suffix.lower() not in (".psarc", ".sloppak"):
            continue
        try:
            current[p.name] = p.stat().st_size
        except OSError:
            continue
    return current


def _watch_tick() -> list[str]:
    """Diff the DLC dir against the previous tick and return the list of
    songs that just finished materializing (confirmed stable). Updates
    the baseline as a side effect."""
    current = _watch_scan_dlc()
    if current is None:
        return []

    # First tick: record a baseline and fire nothing. We only react to
    # transitions during the session — firing for every already-
    # materialized song at startup would replicate the library-wide
    # batch and could blow the disk budget.
    if not _watcher_state["primed"]:
        _watcher_sizes.clear()
        _watcher_sizes.update(current)
        _watcher_state["primed"] = True
        return []

    to_fire: list[str] = []
    for name, cur in current.items():
        prev = _watcher_sizes.get(name)
        if name in _watcher_pending:
            # Saw it go non-zero last tick; confirm the size is stable
            # before parsing (defends against non-atomic writers that
            # stream into place rather than rename a temp file).
            if cur > 0 and cur == _watcher_pending[name]:
                to_fire.append(name)
                del _watcher_pending[name]
            elif cur > 0:
                _watcher_pending[name] = cur          # still growing
            else:
                del _watcher_pending[name]            # re-stubbed mid-write
        elif cur > 0 and (prev == 0 or prev is None):
            # 0-byte stub became real, or a brand-new file appeared.
            _watcher_pending[name] = cur

    # Forget pending entries for files that disappeared this tick.
    for gone in [n for n in _watcher_pending if n not in current]:
        del _watcher_pending[gone]

    _watcher_sizes.clear()
    _watcher_sizes.update(current)
    return to_fire


def _watch_loop():
    log.info("nam_rig_builder watcher started (interval=%ss)", _WATCH_INTERVAL_SEC)
    _watcher_state["running"] = True
    try:
        while not _watcher_stop.is_set():
            try:
                to_fire = _watch_tick()
            except Exception:
                log.exception("nam_rig_builder watcher tick failed")
                _watcher_state["last_error"] = "tick failed (see server log)"
                to_fire = []

            if to_fire:
                settings = _load_settings()
                # No key → nothing to download. We still advanced the
                # baseline above, so adding a key later won't retro-fire
                # the whole library — only songs materialized afterward.
                if settings.get("auto_watch", True) and _get_t3k_client().has_api_access:
                    for name in to_fire:
                        if _watcher_stop.is_set():
                            break
                        _watch_fire(name)

            _watcher_stop.wait(_WATCH_INTERVAL_SEC)
    finally:
        _watcher_state["running"] = False


def _watch_fire(name: str) -> None:
    path = _resolve_song_file(name)
    if path is None:
        return
    try:
        if path.stat().st_size == 0:
            return
    except OSError:
        return
    try:
        result = _auto_download_for_song(name, path)
        _watcher_state["fired_count"] += 1
        _watcher_state["last_fired"] = {
            "filename": name,
            "ts": time.time(),
            "processed": result.get("processed"),
            "downloaded": result.get("downloaded"),
        }
        log.info("nam_rig_builder watcher auto-downloaded %s: %s", name, result)
    except Exception as e:
        log.exception("nam_rig_builder watcher auto-download failed for %s", name)
        _watcher_state["last_error"] = f"{name}: {type(e).__name__}: {e}"


def _start_watcher() -> None:
    global _watcher_thread
    if _watcher_thread is not None and _watcher_thread.is_alive():
        return
    _watcher_stop.clear()
    _watcher_thread = threading.Thread(
        target=_watch_loop, name="nam_rig_builder_watcher", daemon=True,
    )
    _watcher_thread.start()


# ── FastAPI route registration ───────────────────────────────────────


def setup(app, context):
    global _config_dir, _get_dlc_dir, _get_sloppak_cache_dir, _db_path

    _config_dir = Path(context["config_dir"])
    _get_dlc_dir = context["get_dlc_dir"]
    _get_sloppak_cache_dir = context.get("get_sloppak_cache_dir")
    _db_path = str(_config_dir / "nam_tone.db")

    # Force migration on cold start so the table exists by the time the
    # UI first asks for assignments.
    _get_conn()
    _load_settings()

    # Start the background materialization watcher so songs played from
    # Slopsmith's main view (which only triggers cloud_loader to put the
    # PSARC on disk) get their NAM chain auto-downloaded too — not just
    # songs opened from the NAM Rig Builder tab.
    _start_watcher()

    # ── Status / setup ────────────────────────────────────────────────

    @app.get("/api/plugins/nam_rig_builder/status")
    def status():
        rs_map = _load_rs_to_real()
        settings = _load_settings()
        client = _get_t3k_client()
        # Run a tiny harmless request only when we have a key, to verify
        # it's valid and update has_api_access. Cached after first hit.
        if client.api_key and not client.has_api_access:
            try:
                client.search_tones("test", gears="amp", page_size=1)
            except Exception:
                pass
        coverage = {"total": len(rs_map), "by_category": {}}
        for v in rs_map.values():
            coverage["by_category"][v.get("category", "other")] = (
                coverage["by_category"].get(v.get("category", "other"), 0) + 1
            )
        rs_irs_map = _load_rs_cab_to_ir()
        # Count how many of the mapped IRs are actually on disk. The
        # JSON ships with the plugin; the .wav files only land here
        # after the user runs extract_irs.py against their copy of
        # gears.psarc. A fresh install (or a user without Rocksmith)
        # has the map but no audio — the UI uses this distinction to
        # nudge them to extract.
        irs_root = _config_dir / "nam_irs"
        rs_irs_on_disk = 0
        for entry in rs_irs_map.values():
            for f in entry.get("irs") or []:
                if (irs_root / f).exists():
                    rs_irs_on_disk += 1
                    break  # one disk-resident IR per RS entity is enough
        return {
            "rs_to_real_loaded": bool(rs_map),
            "rs_to_real_count": len(rs_map),
            "rs_to_real_by_category": coverage["by_category"],
            "rs_cab_to_ir_loaded": bool(rs_irs_map),
            "rs_cab_to_ir_count": len(rs_irs_map),
            "rs_irs_on_disk": rs_irs_on_disk,
            "has_tone3000_key": bool(settings.get("tone3000_api_key")),
            "tone3000_api_works": client.has_api_access,
            "settings": {
                "min_downloads": settings.get("min_downloads"),
                "aggressive": settings.get("aggressive"),
                "auto_watch": settings.get("auto_watch", True),
            },
            "watcher": {
                "running": _watcher_state["running"],
                "primed": _watcher_state["primed"],
                "fired_count": _watcher_state["fired_count"],
                "last_fired": _watcher_state["last_fired"],
                "last_error": _watcher_state["last_error"],
                "interval_sec": _watcher_state["interval_sec"],
            },
        }

    @app.post("/api/plugins/nam_rig_builder/extract_irs")
    def extract_irs(data: dict = Body(...)):
        """Run extract_irs.py against a user-supplied gears.psarc. The
        IRs are written into <config_dir>/nam_irs/rocksmith/ so the
        nam_tone runtime resolves them via its normal IR path. Returns
        the count of IRs written + RS entities mapped."""
        gears_psarc = data.get("gears_psarc")
        if not gears_psarc or not Path(gears_psarc).exists():
            return JSONResponse({"error": "gears_psarc not found"}, 400)
        script = _plugin_dir / "extract_irs.py"
        irs_root = _config_dir / "nam_irs"
        try:
            result = subprocess.run(
                [sys.executable, str(script), gears_psarc, str(irs_root)],
                capture_output=True,
                timeout=300,
                text=True,
            )
        except subprocess.TimeoutExpired:
            return JSONResponse({"error": "extractor timed out"}, 500)
        if result.returncode != 0:
            return JSONResponse(
                {"error": "extractor failed", "stderr": result.stderr[-2000:]},
                500,
            )
        _invalidate_rs_cab_to_ir()
        return {"ok": True, "stdout": result.stdout, "count": len(_load_rs_cab_to_ir())}

    @app.post("/api/plugins/nam_rig_builder/extract_gear_map")
    def extract_gear_map(data: dict = Body(...)):
        """Run extract_gear_map.py against a user-supplied gears.psarc.
        Returns the new entry count. The script lives in this plugin
        dir; we invoke it as a subprocess using Slopsmith's bundled
        Python so pycryptodome resolves correctly."""
        gears_psarc = data.get("gears_psarc")
        if not gears_psarc or not Path(gears_psarc).exists():
            return JSONResponse({"error": "gears_psarc not found"}, 400)
        script = _plugin_dir / "extract_gear_map.py"
        try:
            result = subprocess.run(
                [sys.executable, str(script), gears_psarc],
                capture_output=True,
                timeout=120,
                text=True,
            )
        except subprocess.TimeoutExpired:
            return JSONResponse({"error": "extractor timed out"}, 500)
        if result.returncode != 0:
            return JSONResponse(
                {"error": "extractor failed", "stderr": result.stderr[-2000:]},
                500,
            )
        _invalidate_rs_to_real()
        return {"ok": True, "stdout": result.stdout, "count": len(_load_rs_to_real())}

    @app.get("/api/plugins/nam_rig_builder/settings")
    def get_settings():
        s = _load_settings()
        # Return the key truncated so we can show "configured" in the
        # UI without leaking the secret to the rendered DOM.
        key = s.get("tone3000_api_key") or ""
        return {
            "min_downloads": s.get("min_downloads", 50),
            "aggressive": s.get("aggressive", False),
            "has_tone3000_key": bool(key),
            "tone3000_api_key_preview": (key[:6] + "…") if key else "",
        }

    @app.post("/api/plugins/nam_rig_builder/settings")
    def update_settings(data: dict = Body(...)):
        # Only persist known keys to avoid junk accumulating in the file.
        allowed = {k: data[k] for k in ("tone3000_api_key", "min_downloads", "aggressive") if k in data}
        _save_settings(allowed)
        return {"ok": True}

    # ── Song / chain inspection ───────────────────────────────────────

    @app.get("/api/plugins/nam_rig_builder/song/{filename:path}")
    def get_song(filename: str):
        path = _resolve_song_file(filename)
        if path is None:
            return JSONResponse({"error": "file not found inside DLC dir"}, 404)

        # 0-byte placeholder = cloud_loader stub. Return a structured
        # signal so the UI can call cloud_loader/materialize before
        # retrying. Status 409 (Conflict) is the closest fit — the
        # resource exists in the index but isn't ready to be read.
        try:
            if path.stat().st_size == 0:
                return JSONResponse(
                    {"error": "cloud_only", "filename": filename,
                     "hint": "POST /api/cloud_loader/materialize?filename=... then retry"},
                    409,
                )
        except OSError:
            pass

        try:
            if path.suffix.lower() == ".sloppak":
                raw_tones = _read_tones_from_sloppak(filename, _get_dlc_dir())
            elif path.suffix.lower() == ".psarc":
                raw_tones = _read_tones_from_psarc(path)
            else:
                return JSONResponse({"error": "unsupported file type"}, 400)
        except ValueError as e:
            # Bad/corrupt PSARC header or non-PSARC bytes with a .psarc
            # extension. The psarc reader raises ValueError in this case
            # — surface it instead of letting it bubble to a 500.
            return JSONResponse({"error": f"unreadable file: {e}"}, 400)
        except Exception as e:
            log.exception("get_song failed for %s", filename)
            return JSONResponse({"error": f"{type(e).__name__}: {e}"}, 500)

        # Map tone_key → existing nam_tone mapping (if any), so the UI
        # can show which tones already have a preset and which don't.
        conn = _get_conn()
        existing_rows = conn.execute(
            "SELECT tone_key, preset_id FROM tone_mappings WHERE filename = ?",
            (filename,),
        ).fetchall()
        existing_by_key = {r[0]: r[1] for r in existing_rows}

        tones: list[dict] = []
        for raw in raw_tones:
            parsed = _parse_tone(raw)
            enriched_chain = [_enrich_chain_piece(p) for p in parsed["chain"]]
            preset_id = existing_by_key.get(parsed["key"])
            # Persisted per-piece bypass, scoped to THIS tone's preset so a
            # bypass saved in another song doesn't bleed in (the gear-global
            # `assigned` lookup can't distinguish songs; preset_id can).
            if preset_id is not None:
                bypass_map = {
                    r[0]: bool(r[1]) for r in conn.execute(
                        "SELECT rs_gear_type, bypassed FROM preset_pieces WHERE preset_id = ?",
                        (preset_id,),
                    )
                }
                for piece in enriched_chain:
                    piece["bypassed"] = bypass_map.get(piece.get("type"), False)
            tones.append({
                "name": parsed["name"],
                "key": parsed["key"],
                "chain": enriched_chain,
                "preset_id": preset_id,
            })
        return {"filename": filename, "tones": tones}

    @app.get("/api/plugins/nam_rig_builder/search")
    def search(rs_gear: str, limit: int = 10, query_override: str = "", gears_override: str = ""):
        """Search tone3000 for a specific Rocksmith gear. Always returns
        a deep-link URL; the candidates list is populated only when the
        API key is set up.

        `query_override` and `gears_override` let the UI re-run the
        search with the user's own guess at the right query when the
        rs_to_real.json mapping turns out to be wrong (e.g. CS-series
        bass amps that don't get a brand match). The override is
        request-scoped — the persisted mapping isn't changed unless
        the user explicitly saves it via /override_query.
        """
        rs_map = _load_rs_to_real()
        info = rs_map.get(rs_gear) or {}
        category = info.get("category", "amp")
        query = query_override.strip() or info.get("tone3000_query") or rs_gear
        gears = gears_override.strip() or info.get("tone3000_gears") or ""
        platform = _PLATFORM_FOR_CATEGORY.get(category, "nam")

        from tone3000_client import Tone3000Client
        deep_link = Tone3000Client.build_search_url(query, gears=gears or None, platform=platform)

        client = _get_t3k_client()
        candidates: list[dict] = []
        if client.has_api_access:
            try:
                resp = client.search_tones(query, gears=gears or None, platform=platform, page_size=min(limit, 25))
                if isinstance(resp, dict):
                    for t in resp.get("data", []):
                        tid = t.get("id")
                        candidates.append({
                            "id": tid,
                            "title": t.get("title"),
                            # Build from the id — the API's own `url`
                            # field returns a 404ing slug (see
                            # Tone3000Client.tone_page_url).
                            "url": Tone3000Client.tone_page_url(tid) if tid is not None else "",
                            "license": t.get("license"),
                            "downloads_count": t.get("downloads_count"),
                            "favorites_count": t.get("favorites_count"),
                            "images": t.get("images"),
                        })
            except Exception:
                log.warning("search failed for %s", rs_gear, exc_info=True)

        return {
            "rs_gear": rs_gear,
            "query": query,
            "gears": gears,
            "platform": platform,
            "deep_link": deep_link,
            "candidates": candidates,
            "has_api_access": client.has_api_access,
        }

    # ── Per-gear query override (persist user discoveries) ──────────

    @app.post("/api/plugins/nam_rig_builder/override_query")
    def override_query(data: dict = Body(...)):
        """Persist a user-supplied tone3000 query/gears override for
        one rs_gear into rs_to_real.json.

        Use case: rs_to_real.json's auto-generated query for a
        pseudonym amp (e.g. `Bass_Amp_CS75B` → "Cs 75B") returns 0
        candidates from tone3000. The user finds the actual real-world
        model by editing the query in the Sugerir modal ("Ampeg SVT")
        and clicks "Guardar como override" — we patch the JSON so
        future batches and lookups use the corrected query.

        Body: `{rs_gear, query, gears?, platform?}`. `query` is
        required; `gears` and `platform` are optional and only
        written if non-empty (so partial overrides don't clobber
        the category-derived defaults).
        """
        rs_gear = (data.get("rs_gear") or "").strip()
        new_query = (data.get("query") or "").strip()
        new_gears = (data.get("gears") or "").strip()
        if not rs_gear or not new_query:
            return JSONResponse({"error": "rs_gear and query required"}, 400)
        rs_map = _load_rs_to_real()
        if rs_gear not in rs_map:
            return JSONResponse(
                {"error": f"rs_gear {rs_gear} not present in rs_to_real.json"},
                404,
            )
        rs_map[rs_gear]["tone3000_query"] = new_query
        if new_gears:
            rs_map[rs_gear]["tone3000_gears"] = new_gears
        path = _plugin_dir / "rs_to_real.json"
        path.write_text(json.dumps(rs_map, indent=2, sort_keys=True))
        _invalidate_rs_to_real()
        # The tone3000 client caches each search URL for 7 days. Our
        # override changes the URL so the new query naturally misses
        # the cache — no explicit invalidation needed.
        return {"ok": True, "rs_gear": rs_gear, "query": new_query, "gears": new_gears}

    # ── v3: per-gear manual auto-download (used from the Sugerir modal) ─

    @app.post("/api/plugins/nam_rig_builder/download_for_gear")
    def download_for_gear(data: dict = Body(...)):
        """Manually pull a tone3000 capture for a single Rocksmith gear.

        The UI calls this from the per-candidate "Descargar y asignar"
        button inside the Sugerir modal. Reuses the same
        `_download_candidate` helper the batch worker uses so naming,
        deduplication, and ffmpeg normalization stay identical.

        Body: `{rs_gear: "Amp_AT120", tone3000_id: 12345}`.

        Returns `{kind, file}` on success — the UI stores those on the
        in-memory piece so the next "Guardar preset" picks them up,
        the same way it does for a manually-uploaded file.
        """
        rs_gear = data.get("rs_gear", "")
        tone3000_id = data.get("tone3000_id")
        if not rs_gear or not tone3000_id:
            return JSONResponse({"error": "rs_gear and tone3000_id required"}, 400)
        settings = _load_settings()
        info = _load_rs_to_real().get(rs_gear) or {}
        category = info.get("category", "amp")
        # Manual downloads bypass the batch disk budget — the user
        # explicitly asked for this one file.
        global _batch_disk_bytes
        prev = _batch_disk_bytes
        _batch_disk_bytes = 0
        try:
            result = _download_candidate(
                tone3000_id=int(tone3000_id),
                is_ir=(category == "cab"),
                rs_gear=rs_gear,
                settings=settings,
            )
        finally:
            _batch_disk_bytes = prev
        if not result:
            return JSONResponse(
                {"error": "download failed — check that the tone3000 key is valid and the tone has a downloadable model"},
                502,
            )
        kind, fname = result
        # Persist the assignment so the gear leaves the Pendientes list
        # and the song actually plays through the downloaded capture.
        # Without this, the file sat on disk unreferenced and coverage
        # kept reporting the gear as pending.
        assigned = _assign_file_to_gear(rs_gear, kind, fname, int(tone3000_id))
        return {"ok": True, "kind": kind, "file": fname, **assigned}

    # ── Auto-download for a single song (triggered on UI open) ──────

    @app.post("/api/plugins/nam_rig_builder/auto_download_song")
    def auto_download_song(data: dict = Body(...)):
        """Run the same per-piece auto-download flow the batch worker
        does, but scoped to one song. Triggered by the UI when the
        user opens a song with the API key configured — the goal is
        that opening a cloud-loaded song fully materializes its NAM
        chain end-to-end without further clicks.

        Body: `{filename}`. The plugin parses tones, dedupes gear
        across the song's tones, picks tone3000 candidates under the
        current policy, downloads what's missing, and persists
        preset rows. Pieces with an existing assignment in
        `preset_pieces` are skipped — re-opening a song is free.

        Returns counts: `{processed, downloaded, skipped_assigned,
        skipped_no_candidate, failed}`.
        """
        filename = data.get("filename")
        if not filename:
            return JSONResponse({"error": "filename required"}, 400)
        path = _resolve_song_file(filename)
        if path is None:
            return JSONResponse({"error": "file not found"}, 404)
        try:
            if path.stat().st_size == 0:
                return JSONResponse(
                    {"error": "file is a cloud-only placeholder; materialize it first"},
                    409,
                )
        except OSError:
            return JSONResponse({"error": "could not stat file"}, 500)

        if not _get_t3k_client().has_api_access:
            return JSONResponse({"error": "no tone3000 API key configured"}, 400)

        try:
            return _auto_download_for_song(filename, path)
        except ValueError as e:
            return JSONResponse({"error": f"unreadable file: {e}"}, 400)
        except Exception as e:
            log.exception("auto_download_song failed for %s", filename)
            return JSONResponse({"error": f"{type(e).__name__}: {e}"}, 500)

    # ── Persist a preset (manual save from UI) ────────────────────────

    @app.post("/api/plugins/nam_rig_builder/save_preset")
    def save_preset(data: dict = Body(...)):
        filename = data.get("filename")
        tone_key = data.get("tone_key", "")
        name = data.get("name") or f"{filename}::{tone_key or 'tone'}"
        pieces = data.get("pieces") or []
        if not filename or not isinstance(pieces, list):
            return JSONResponse({"error": "filename and pieces required"}, 400)
        try:
            preset_id = _persist_preset_chain(
                filename=filename,
                tone_key=tone_key,
                name=name,
                pieces=pieces,
                input_gain=float(data.get("input_gain", 1.0)),
                output_gain=float(data.get("output_gain", 0.5)),
                gate_threshold=float(data.get("gate_threshold", -60.0)),
                assigned_mode=data.get("assigned_mode", "manual"),
            )
        except Exception as e:
            log.exception("save_preset failed")
            return JSONResponse({"error": f"{type(e).__name__}: {e}"}, 500)
        return {"ok": True, "preset_id": preset_id}

    # ── Full-chain native preset (experimental multi-NAM preview) ─────
    @app.get("/api/plugins/nam_rig_builder/native_preset_full/{preset_id}")
    def native_preset_full(preset_id: int):
        """Build a native_preset that sends the WHOLE chain to the engine:
        every NAM piece as its own type-1 stage (in signal-flow order) plus
        the cab IR as type-2 — unlike nam_tone's get_native_preset, which
        emits only the single primary NAM + IR. Used by the "Escuchar"
        preview to test/realise multi-NAM playback (pedal → amp → cab)
        without touching the bundle. Returns `nam_stage_count` so the UI/
        operator can see how many NAM stages were built, and the engine's
        `slotsLoaded` (logged client-side) reveals how many it accepted.
        """
        conn = _get_conn()
        prow = conn.execute(
            "SELECT id, name, input_gain, output_gain, gate_threshold "
            "FROM presets WHERE id = ?",
            (preset_id,),
        ).fetchone()
        if not prow:
            return JSONResponse({"error": "preset not found"}, 404)
        _, name, input_gain, output_gain, gate_threshold = prow

        rows = conn.execute(
            "SELECT slot, kind, file, rs_gear_type, bypassed FROM preset_pieces WHERE preset_id = ? "
            "ORDER BY slot_order",
            (preset_id,),
        ).fetchall()

        models_dir = (_config_dir / "nam_models") if _config_dir else None
        irs_dir = (_config_dir / "nam_irs") if _config_dir else None

        # (slot, file, rs_gear, bypassed) per NAM piece, ordered by signal flow.
        nam_rows = [(r[0], r[2], r[3], bool(r[4])) for r in rows if r[1] == "nam" and r[2]]
        # Order NAM stages by signal flow; unknown slots keep their stored
        # order after the known ones.
        def _rank(slot: str) -> int:
            return _CHAIN_NAM_ORDER.index(slot) if slot in _CHAIN_NAM_ORDER else len(_CHAIN_NAM_ORDER)
        nam_rows.sort(key=lambda sr: _rank(sr[0]))

        chain: list[dict] = []
        missing: list[str] = []
        for slot, file, gear, bypassed in nam_rows:
            path = _safe_child(models_dir, file)
            if not path or not path.exists():
                missing.append(file)
                continue
            chain.append({
                "type": 1,
                "name": Path(file).stem,
                "path": str(path),
                # Persisted bypass = the engine passes signal THROUGH this
                # stage (not silence). The UI can still flip it live.
                "bypassed": bypassed,
                "slot": slot,
                "rs_gear": gear,
                # Unity in/out for every NAM so intermediate stages feed the
                # next at full level; final loudness is set on the IR.
                "state": _state_b64({
                    "modelPath": str(path),
                    "inputLevel": 1.0,
                    "outputLevel": 1.0,
                }),
            })

        # One cab IR at the tail (prefer the cabinet slot).
        ir_rows = [(r[0], r[2], r[3], bool(r[4])) for r in rows if r[1] in ("ir", "rs_ir") and r[2]]
        ir_pick = next((row for row in ir_rows if row[0] == "cabinet"), None)
        if ir_pick is None and ir_rows:
            ir_pick = ir_rows[0]
        if ir_pick:
            ir_slot, ir_file, ir_gear, ir_bypassed = ir_pick
            ir_path = _safe_child(irs_dir, ir_file)
            if ir_path and ir_path.exists():
                chain.append({
                    "type": 2,
                    "name": Path(ir_file).stem,
                    "path": str(ir_path),
                    "bypassed": ir_bypassed,
                    "slot": ir_slot,
                    "rs_gear": ir_gear,
                    "state": _state_b64({"irPath": str(ir_path), "gain": float(output_gain)}),
                })
            else:
                missing.append(ir_file)

        return {
            "id": preset_id,
            "name": name,
            "input_gain": input_gain,
            "output_gain": output_gain,
            "gate_threshold": gate_threshold,
            "native_preset": {"version": 1, "chain": chain},
            "nam_stage_count": sum(1 for s in chain if s["type"] == 1),
            "missing": missing,
        }

    # ── Single-stage audition (catalog "Escuchar") ────────────────────
    @app.get("/api/plugins/nam_rig_builder/native_preset_one")
    def native_preset_one(file: str, kind: str = "nam", gain: float = 0.5):
        """A native_preset with ONE stage from a single file, to audition a
        gear's capture in isolation."""
        models_dir = (_config_dir / "nam_models") if _config_dir else None
        irs_dir = (_config_dir / "nam_irs") if _config_dir else None
        if kind in ("ir", "rs_ir"):
            p = _safe_child(irs_dir, file)
            if not p or not p.exists():
                return JSONResponse({"error": "ir not found"}, 404)
            stage = {"type": 2, "name": Path(file).stem, "path": str(p),
                     "bypassed": False,
                     "state": _state_b64({"irPath": str(p), "gain": float(gain)})}
        else:
            p = _safe_child(models_dir, file)
            if not p or not p.exists():
                return JSONResponse({"error": "model not found"}, 404)
            stage = {"type": 1, "name": Path(file).stem, "path": str(p),
                     "bypassed": False,
                     "state": _state_b64({"modelPath": str(p), "inputLevel": 1.0,
                                          "outputLevel": float(gain)})}
        return {"native_preset": {"version": 1, "chain": [stage]}}

    # ── Gear catalog (grouped by type, with parenting + photo) ────────
    @app.get("/api/plugins/nam_rig_builder/gear_catalog")
    def gear_catalog():
        """Every Rocksmith gear referenced by a mapped song, grouped by
        category, with what it's parented to (real make/model + assigned
        capture/file) and a tone3000 photo when resolvable from cache."""
        from tone3000_client import Tone3000Client
        conn = _get_conn()
        rs_map = _load_rs_to_real()
        img_idx = _tone_image_index()

        # Best preset_piece per gear: prefer a row with a file, else latest.
        rows = conn.execute(
            "SELECT rs_gear_type, kind, file, tone3000_id, id FROM preset_pieces "
            "ORDER BY id DESC"
        ).fetchall()
        best: dict[str, dict] = {}
        for gear, kind, file, t3kid, _id in rows:
            has_file = bool(file)
            cur = best.get(gear)
            if cur is None or (has_file and not cur["has_file"]):
                best[gear] = {"kind": kind, "file": file,
                              "tone3000_id": t3kid, "has_file": has_file}

        cats: dict[str, list] = {}
        for gear, b in best.items():
            info = rs_map.get(gear) or {}
            category = info.get("category") or "other"
            t3kid = b["tone3000_id"]
            meta = img_idx.get(t3kid) if t3kid else None
            cats.setdefault(category, []).append({
                "rs_gear": gear,
                "real_name": info.get("name") or gear,
                "make": info.get("make", ""),
                "model": info.get("model", ""),
                "category": category,
                "assigned": b["has_file"],
                "kind": b["kind"],
                "file": b["file"],
                "tone3000_id": t3kid,
                "tone3000_title": (meta or {}).get("title"),
                "image": (meta or {}).get("image"),
                "tone3000_url": Tone3000Client.tone_page_url(t3kid) if t3kid else None,
            })
        for lst in cats.values():
            lst.sort(key=lambda g: (not g["assigned"], (g["real_name"] or "").lower()))

        order = ["amp", "pedal", "cab", "rack", "other"]
        ordered = {c: cats[c] for c in order if c in cats}
        for c in cats:
            ordered.setdefault(c, cats[c])
        return {"categories": ordered,
                "counts": {c: len(v) for c, v in ordered.items()}}

    # ── Download a candidate to audition it (no assign) ───────────────
    @app.post("/api/plugins/nam_rig_builder/audition_candidate")
    def audition_candidate(data: dict = Body(...)):
        """Download the best model for a tone3000 tone_id into
        nam_models/nam_irs WITHOUT assigning, so the UI can audition a
        search candidate. Body {rs_gear, tone3000_id}. Returns {kind, file}."""
        tone3000_id = data.get("tone3000_id")
        if tone3000_id is None:
            return JSONResponse({"error": "tone3000_id required"}, 400)
        rs_gear = data.get("rs_gear") or "audition"
        category = (_load_rs_to_real().get(rs_gear) or {}).get("category", "amp")
        try:
            res = _download_candidate(
                tone3000_id=int(tone3000_id), is_ir=(category == "cab"),
                rs_gear=rs_gear, settings=_load_settings(),
            )
        except Exception as e:
            log.exception("audition_candidate failed")
            return JSONResponse({"error": f"{type(e).__name__}: {e}"}, 500)
        if not res:
            return JSONResponse({"error": "no downloadable model (or disk budget reached)"}, 502)
        kind, file = res
        return {"kind": kind, "file": file}

    # ── Batch ─────────────────────────────────────────────────────────

    @app.post("/api/plugins/nam_rig_builder/batch_all")
    def batch_all():
        global _batch_thread
        with _batch_lock:
            if _batch_state["running"]:
                return JSONResponse({"error": "batch already running"}, 409)
            _batch_state.update({
                "running": True,
                "progress": 0,
                "total": 0,
                "assigned": 0,
                "skipped": 0,
                "pending": [],
                "log": [],
                "started_at": None,
                "finished_at": None,
            })
        _batch_thread = threading.Thread(target=_batch_worker, name="nam_rig_builder_batch", daemon=True)
        _batch_thread.start()
        return {"ok": True}

    @app.get("/api/plugins/nam_rig_builder/batch_status")
    def batch_status():
        with _batch_lock:
            # Return a shallow copy so log list mutations during render
            # can't race with the worker.
            return dict(_batch_state, log=list(_batch_state["log"]))

    # ── Coverage / pendientes ─────────────────────────────────────────

    @app.get("/api/plugins/nam_rig_builder/coverage")
    def coverage():
        """Pending = preset_pieces with kind='none' or missing file."""
        conn = _get_conn()
        rows = conn.execute(
            "SELECT rs_gear_type, COUNT(*) AS n, "
            "  SUM(CASE WHEN kind='none' OR file IS NULL OR file='' THEN 1 ELSE 0 END) AS pending "
            "FROM preset_pieces "
            "GROUP BY rs_gear_type "
            "ORDER BY pending DESC, n DESC"
        ).fetchall()
        rs_map = _load_rs_to_real()
        out = []
        for r in rows:
            rs = r[0]
            info = rs_map.get(rs) or {}
            out.append({
                "rs_gear": rs,
                "total_chain_slots": r[1],
                "pending_chain_slots": r[2],
                "name": info.get("name", rs),
                "category": info.get("category", "other"),
                "tone3000_query": info.get("tone3000_query", rs),
            })
        return {"items": out}

    @app.get("/api/plugins/nam_rig_builder/list_songs")
    def list_songs(q: str = "", limit: int = 50):
        """Return playable songs from DLC dir, optionally filtered by
        substring on the filename. Each entry carries a `materialized`
        flag so the UI can mark cloud-only stubs (0-byte placeholders
        for files that still live in Google Drive) and trigger
        cloud_loader/materialize on click.
        """
        dlc = _get_dlc_dir() if _get_dlc_dir else None
        if not dlc:
            return {"songs": []}
        q_lower = q.lower()
        matches: list[dict] = []
        for p in sorted(dlc.iterdir()):
            if p.suffix.lower() not in (".psarc", ".sloppak"):
                continue
            if q_lower and q_lower not in p.name.lower():
                continue
            try:
                size = p.stat().st_size
            except OSError:
                continue
            matches.append({
                "name": p.name,
                "size": size,
                "materialized": size > 0,
            })
            if len(matches) >= limit:
                break
        return {"songs": matches}
