#!/usr/bin/make -f

NAME = SendInTheClones

FILES_DSP = \
	SendInTheClonesPlugin.cpp

FILES_UI = \
	SendInTheClones_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
