#!/usr/bin/make -f

NAME = PlanePhase

FILES_DSP = \
	PlanePhasePlugin.cpp

FILES_UI = \
	PlanePhase_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
