#!/usr/bin/make -f

NAME = MarshallGuvnorPlus

FILES_DSP = \
	MarshallGuvnorPlusPlugin.cpp

FILES_UI = \
	MarshallGuvnorPlus_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
