#!/usr/bin/make -f
# Dustup CDN — Ashdown ABM EVO Bass Magnifier head model (DPF plugin)

NAME = DustupCDN

FILES_DSP = \
	DustupPlugin.cpp

FILES_UI = \
	Dustup_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
