#!/usr/bin/make -f

NAME = Phaser363

FILES_DSP = \
	Phaser363Plugin.cpp

FILES_UI = \
	Phaser363_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
