#!/usr/bin/make -f

NAME = ShaverPhaser

FILES_DSP = \
	ShaverPhaserPlugin.cpp

FILES_UI = \
	ShaverPhaser_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
