#!/usr/bin/make -f

NAME = USWah

FILES_DSP = \
	USWahPlugin.cpp

FILES_UI = \
	USWah_ui.cpp

FILES_UI = \
	EN30_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
