#!/usr/bin/make -f
NAME = StereoAnalogVibe
FILES_DSP = StereoAnalogVibePlugin.cpp
FILES_UI = StereoAnalogVibe_ui.cpp
DPF_PATH ?= ../DPF
include $(DPF_PATH)/Makefile.plugins.mk
TARGETS += vst3
all: $(TARGETS)
