#!/usr/bin/make -f

NAME = BassSubOctave

FILES_DSP = \
	BassSubOctavePlugin.cpp

FILES_UI = \
	BassSubOctave_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
