#!/usr/bin/make -f

NAME = BakedRotatoe

FILES_DSP = \
	BakedRotatoePlugin.cpp

FILES_UI = \
	BakedRotatoe_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
