#!/usr/bin/make -f

NAME = TremOle

FILES_DSP = \
	TremOlePlugin.cpp

FILES_UI = \
	TremOle_ui.cpp

FILES_UI = \
	TW22_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
