#!/usr/bin/make -f

NAME = Swole

FILES_DSP = \
	SwolePlugin.cpp

FILES_UI = \
	Swole_ui.cpp

FILES_UI = \
	DualRect_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
