#!/usr/bin/make -f

NAME = CaptainFuzzle

FILES_DSP = \
	CaptainFuzzlePlugin.cpp

FILES_UI = \
	CaptainFuzzle_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
