#!/usr/bin/make -f

NAME = ClassicFlanger

FILES_DSP = \
	ClassicFlangerPlugin.cpp

FILES_UI = \
	ClassicFlanger_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
