#!/usr/bin/make -f

NAME = MarshallSupervibe

FILES_DSP = \
	MarshallSupervibePlugin.cpp

FILES_UI = \
	MarshallSupervibe_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
