#!/usr/bin/make -f

NAME = RangeBooster

FILES_DSP = \
	RangeBoosterPlugin.cpp

FILES_UI = \
	RangeBooster_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
