#!/usr/bin/make -f

NAME = FuzzWasHe

FILES_DSP = \
	FuzzWasHePlugin.cpp

FILES_UI = \
	FuzzWasHe_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
