#!/usr/bin/make -f

NAME = UKWah

FILES_DSP = \
	UKWahPlugin.cpp

FILES_UI = \
	UKWah_ui.cpp

FILES_UI = \
	DSL100_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
