#!/usr/bin/make -f

NAME = TubeSpring

FILES_DSP = \
	TubeSpringPlugin.cpp

FILES_UI = \
	TubeSpring_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
