#!/usr/bin/make -f

NAME = BassFilterDelay

FILES_DSP = \
	BassFilterDelayPlugin.cpp

FILES_UI = \
	BassFilterDelay_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
