#!/usr/bin/make -f

NAME = EightiesFlanger

FILES_DSP = \
	EightiesFlangerPlugin.cpp

FILES_UI = \
	EightiesFlanger_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
