#!/usr/bin/make -f

NAME = MultiTrem

FILES_DSP = \
	MultiTremPlugin.cpp

FILES_UI = \
	MultiTrem_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
