#!/usr/bin/make -f

NAME = StandardDistortion

FILES_DSP = \
	StandardDistortionPlugin.cpp

FILES_UI = \
	StandardDistortion_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
