#!/usr/bin/make -f

NAME = AlloyDistortion

FILES_DSP = \
	AlloyDistortionPlugin.cpp

FILES_UI = \
	AlloyDistortion_ui.cpp

DPF_PATH ?= ../DPF

include $(DPF_PATH)/Makefile.plugins.mk

TARGETS += vst3

all: $(TARGETS)
