#!/usr/bin/make -f
NAME = StereoTubeTrem
FILES_DSP = StereoTubeTremPlugin.cpp
FILES_UI = StereoTubeTrem_ui.cpp
DPF_PATH ?= ../DPF
include $(DPF_PATH)/Makefile.plugins.mk
TARGETS += vst3
all: $(TARGETS)
